env:
  es2021: true
  node: true
  browser: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign: [2, { "props": false }]
